spring:
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  profiles:
    active:
      - local
    group:
      local:
        - db-local
        - common
      dev:
        - db-dev
        - common
    include:
      - db
      - common